#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <test_icons.h>

/* 来自私有库 mymath；因为 application.fam 里配置了 fap_include_paths=["include"]，
   所以这里可以直接 include 到 lib/mymath/include/mymath.h */
#include <mymath.h>

int32_t test_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm test!");

    // 调用私有库里的函数
    FURI_LOG_I("TEST", "my_add(2, 3) = %d", my_add(2, 3));
    // 因为 cdefines 定义了 MYMATH_ENABLE_MUL，这里会返回 20；否则返回 0
    FURI_LOG_I("TEST", "my_mul(4, 5) = %d", my_mul(4, 5));

    return 0;
}
