#include <furi.h>
#include <gui/canvas.h>
#include <gui/gui.h>
#include <gui/view.h>
#include <gui/view_dispatcher.h>
#include <gui/modules/submenu.h>
#include <gui/modules/text_box.h>
#include <gui/modules/widget.h>
#include <input/input.h>
#include <storage/storage.h>
#include <toolbox/stream/file_stream.h>
#include <toolbox/stream/stream.h>

/* generated by fbt from .png files in images folder */
#include <asset_use_icons.h>

#define TAG "AssetUse"

typedef enum {
    AssetUseViewMenu,
    AssetUseViewIcon,
    AssetUseViewAnimation,
    AssetUseViewFiles,
} AssetUseViewId;

typedef enum {
    AssetUseMenuIcon,
    AssetUseMenuAnimation,
    AssetUseMenuFiles,
} AssetUseMenuIndex;

typedef struct {
    IconAnimation* animation;
    bool running;
} AssetUseAnimationModel;

typedef struct {
    Gui* gui;
    ViewDispatcher* view_dispatcher;
    Submenu* submenu;
    Widget* widget;
    TextBox* text_box;
    View* animation_view;
    IconAnimation* animation;
    FuriString* file_text;
} AssetUseApp;

static uint32_t asset_use_exit_app(void* context) {
    UNUSED(context);
    return VIEW_NONE;
}

static uint32_t asset_use_back_to_menu(void* context) {
    UNUSED(context);
    return AssetUseViewMenu;
}

// 把文件里面的内容读取出来, 追加在output字符串里面, 并在前面加上标题和路径
static void asset_use_append_file(
    Storage* storage,
    FuriString* output,
    const char* path,
    const char* title) {
    Stream* stream = file_stream_alloc(storage);
    FuriString* line = furi_string_alloc();

    furi_string_cat_printf(output, "[%s]\nPath: %s\n", title, path);
    if(file_stream_open(stream, path, FSAM_READ, FSOM_OPEN_EXISTING)) {
        while(stream_read_line(stream, line)) {
            furi_string_replace_all(line, "\r", "");
            furi_string_replace_all(line, "\n", "");
            furi_string_cat(output, furi_string_get_cstr(line));
            furi_string_cat(output, "\n");
        }
        file_stream_close(stream);
    } else {
        furi_string_cat(output, "Failed to open file.\n");
        FURI_LOG_E(TAG, "Failed to open asset file: %s", path);
    }

    furi_string_cat(output, "\n");
    furi_string_free(line);
    stream_free(stream);
}

static void asset_use_prepare_icon_demo(AssetUseApp* app) {
    widget_reset(app->widget);

    widget_add_string_element(
        app->widget, 4, 2, AlignLeft, AlignTop, FontPrimary, "Static Icon Asset");
    widget_add_icon_element(app->widget, 4, 18, &I_AssetDolphin_71x25);
    widget_add_text_box_element(
        app->widget,
        79,
        18,
        45,
        30,
        AlignLeft,
        AlignTop,
        "PNG from images/\nbecomes\nI_AssetDolphin_71x25",
        true);
    widget_add_string_element(
        app->widget, 4, 61, AlignLeft, AlignBottom, FontSecondary, "Back: menu");
}

static void asset_use_prepare_files_demo(AssetUseApp* app) {
    text_box_reset(app->text_box);
    text_box_set_font(app->text_box, TextBoxFontText);
    text_box_set_focus(app->text_box, TextBoxFocusStart);

    furi_string_printf(
        app->file_text,
        "Loaded from APP_ASSETS_PATH(...)\n"
        "These files come from the app's files/ folder.\n\n");

    // 请求存储服务, 打开文件, 读取内容, 追加到file_text字符串里面
    Storage* storage = furi_record_open(RECORD_STORAGE);
    asset_use_append_file(
        storage,
        app->file_text,
        APP_ASSETS_PATH("docs/readme.txt"),
        "docs/readme.txt");
    asset_use_append_file(
        storage,
        app->file_text,
        APP_ASSETS_PATH("config/demo.ini"),
        "config/demo.ini");
    furi_record_close(RECORD_STORAGE);

    // 设置文本框的内容为file_text字符串的内容, 这样就可以显示文件内容了
    text_box_set_text(app->text_box, furi_string_get_cstr(app->file_text));
}

static void asset_use_menu_callback(void* context, uint32_t index) {
    AssetUseApp* app = context;

    switch(index) {
    case AssetUseMenuIcon:
        asset_use_prepare_icon_demo(app);
        view_dispatcher_switch_to_view(app->view_dispatcher, AssetUseViewIcon);
        break;
    case AssetUseMenuAnimation:
        view_dispatcher_switch_to_view(app->view_dispatcher, AssetUseViewAnimation);
        break;
    case AssetUseMenuFiles:
        asset_use_prepare_files_demo(app);
        view_dispatcher_switch_to_view(app->view_dispatcher, AssetUseViewFiles);
        break;
    default:
        break;
    }
}

// 每隔一段时间调用一次, 用于绘制动画视图的内容, 包括标题、文件夹路径、动画和提示信息
static void asset_use_animation_draw(Canvas* canvas, void* model_) {
    AssetUseAnimationModel* model = model_;

    canvas_clear(canvas);
    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str(canvas, 4, 10, "Animation Asset");

    canvas_set_font(canvas, FontSecondary);
    canvas_draw_str(canvas, 4, 22, "Folder -> A_AssetAlarm_47x39");
    canvas_draw_frame(canvas, 38, 18, 52, 43);
    // 绘制动画, 这里调用了icon_animation_get_data函数获取当前帧的图像数据, 并绘制在指定位置
    // 底层 IconAnimation 定时器每 tick 会把 frame 加一
    canvas_draw_icon_animation(canvas, 40, 20, model->animation); 
    canvas_draw_str(
        canvas,
        4,
        61,
        model->running ? "OK: pause  Back: menu" : "OK: start  Back: menu");
}

// 处理动画视图的输入事件, 当按下OK键时, 切换动画的运行状态
static bool asset_use_animation_input(InputEvent* event, void* context) {
    AssetUseApp* app = context;

    if((event->type != InputTypeShort) || (event->key != InputKeyOk)) {
        return false;
    }

    bool should_start = false;
    with_view_model(
        app->animation_view,
        AssetUseAnimationModel * model,
        {
            model->running = !model->running;
            should_start = model->running;
        },
        true);

    if(should_start) {
        icon_animation_start(app->animation);
    } else {
        icon_animation_stop(app->animation);
    }

    return true;
}

// 进入动画视图时, 设置动画模型的running为true, 并启动动画
static void asset_use_animation_enter(void* context) {
    AssetUseApp* app = context;

    with_view_model(
        app->animation_view,
        AssetUseAnimationModel * model,
        { model->running = true; },  // 设置开始运行动画的标志
        true);
    icon_animation_start(app->animation); // 启动动画, 启动一个定时器, 定时调用icon_animation_next_frame函数
}

// 退出动画视图时, 设置动画模型的running为false, 并停止动画
static void asset_use_animation_exit(void* context) {
    AssetUseApp* app = context;

    icon_animation_stop(app->animation);
    with_view_model(
        app->animation_view,
        AssetUseAnimationModel * model,
        { model->running = false; },
        false);
}

static AssetUseApp* asset_use_alloc(void) {
    AssetUseApp* app = malloc(sizeof(AssetUseApp));

    app->gui = furi_record_open(RECORD_GUI);
    app->view_dispatcher = view_dispatcher_alloc();
    app->submenu = submenu_alloc();
    app->widget = widget_alloc();
    app->text_box = text_box_alloc();
    app->animation_view = view_alloc();
    app->animation = icon_animation_alloc(&A_AssetAlarm_47x39); // 创建一个动画对象, 使用A_AssetAlarm_47x39文件夹里面的帧图片
    app->file_text = furi_string_alloc();

    view_dispatcher_attach_to_gui(app->view_dispatcher, app->gui, ViewDispatcherTypeFullscreen);

    // 配置菜单
    submenu_set_header(app->submenu, "Assets Demo");
    submenu_add_item(app->submenu, "Static icon", AssetUseMenuIcon, asset_use_menu_callback, app);
    submenu_add_item(
        app->submenu, "Animated icon", AssetUseMenuAnimation, asset_use_menu_callback, app);
    submenu_add_item(app->submenu, "Resource files", AssetUseMenuFiles, asset_use_menu_callback, app);
    view_set_previous_callback(submenu_get_view(app->submenu), asset_use_exit_app);

    view_set_previous_callback(widget_get_view(app->widget), asset_use_back_to_menu);

    text_box_set_font(app->text_box, TextBoxFontText);
    text_box_set_focus(app->text_box, TextBoxFocusStart);
    view_set_previous_callback(text_box_get_view(app->text_box), asset_use_back_to_menu);

    // 配置动画视图
    // 分配一个锁定模型, 用于存储动画的状态
    view_allocate_model(
        app->animation_view, ViewModelTypeLocking, sizeof(AssetUseAnimationModel));
    // 设置动画视图的模型, 并初始化动画和running状态
    with_view_model(
        app->animation_view,
        AssetUseAnimationModel * model,
        {
            model->animation = app->animation;
            model->running = false;
        },
        false);
    view_set_context(app->animation_view, app);
    view_set_draw_callback(app->animation_view, asset_use_animation_draw); // 设置动画视图的绘制回调函数, 用于绘制动画和文本
    view_set_input_callback(app->animation_view, asset_use_animation_input);
    view_set_enter_callback(app->animation_view, asset_use_animation_enter);
    view_set_exit_callback(app->animation_view, asset_use_animation_exit);
    view_set_previous_callback(app->animation_view, asset_use_back_to_menu);
    // 进行绑定, 动画定时器推进到下一帧后，就会通知 view 刷新
    view_tie_icon_animation(app->animation_view, app->animation);

    view_dispatcher_add_view(
        app->view_dispatcher, AssetUseViewMenu, submenu_get_view(app->submenu));
    view_dispatcher_add_view(app->view_dispatcher, AssetUseViewIcon, widget_get_view(app->widget));
    view_dispatcher_add_view(
        app->view_dispatcher, AssetUseViewAnimation, app->animation_view);
    view_dispatcher_add_view(app->view_dispatcher, AssetUseViewFiles, text_box_get_view(app->text_box));
    view_dispatcher_switch_to_view(app->view_dispatcher, AssetUseViewMenu);

    return app;
}

static void asset_use_free(AssetUseApp* app) {
    furi_assert(app);

    view_dispatcher_remove_view(app->view_dispatcher, AssetUseViewMenu);
    view_dispatcher_remove_view(app->view_dispatcher, AssetUseViewIcon);
    view_dispatcher_remove_view(app->view_dispatcher, AssetUseViewAnimation);
    view_dispatcher_remove_view(app->view_dispatcher, AssetUseViewFiles);

    icon_animation_stop(app->animation);
    icon_animation_free(app->animation);
    view_free(app->animation_view);
    text_box_free(app->text_box);
    widget_free(app->widget);
    submenu_free(app->submenu);
    furi_string_free(app->file_text);
    view_dispatcher_free(app->view_dispatcher);
    furi_record_close(RECORD_GUI);

    free(app);
}

int32_t asset_use_app(void* p) {
    UNUSED(p);

    AssetUseApp* app = asset_use_alloc();
    view_dispatcher_run(app->view_dispatcher);
    asset_use_free(app);

    return 0;
}
